# ================================================
#    __  __                
#   |  \/  |_   _ ___  ___ 
#   | |\/| | | | / __|/ _ \
#   | |  | | |_| \__ \  __/
#   |_|  |_|\__,_|___/\___|
#                          
# ================================================

# -----------------------------------------------
# Input and Output Configuration
# -----------------------------------------------
# Specify the paths for input and output folders.
# The input folder should contain preprocessed images from Chisel.
# The output folder will store the organized dataset.

input_folder: "path/to/preprocessed_images"
output_folder: "path/to/output_dataset"

# -----------------------------------------------
# Dataset Splitting Configuration
# -----------------------------------------------
# Define the ratios for splitting the dataset into training, validation, and test sets.
# The sum of these ratios should equal 1.0.

split_ratios:
  - 0.8  # training set
  - 0.1  # validation set
  - 0.1  # test set

# -----------------------------------------------
# Data Augmentation Settings
# -----------------------------------------------
# Configure data augmentation to increase dataset variety and prevent overfitting.

augment: true  # Set to false to disable augmentation

# Types of augmentation to apply
augmentation_types:
  - rotate
  - flip_horizontal
  - mixup
  - cutmix

# Multiplier for augmentation (e.g., 2 will double the dataset size)
augmentation_multiplier: 1

# -----------------------------------------------
# Quality Control Parameters
# -----------------------------------------------
# Set minimum requirements for images to be included in the dataset.

min_size: 128  # Minimum size in pixels (width and height)
allowed_formats:
  - JPEG
  - PNG

# -----------------------------------------------
# Advanced Settings
# -----------------------------------------------
# Additional options for dataset creation and management.

stratify: true  # Maintain class distribution across splits

# -----------------------------------------------
# Label Mapping
# -----------------------------------------------
# Define the mapping of categories to numerical labels.
# Modify this section to match your dataset's categories.

label_mapping:
  Category1: 0
  Category2: 1
  Unknown: -1

# -----------------------------------------------
# Logging Configuration
# -----------------------------------------------
# Specify the file where logs will be stored.
# Ensure that the application has write permissions to this directory.

log_file: "muse_log.txt"
log_level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL

# ================================================
#                End of Configuration
# ================================================
