version: 2
updates:
  # Main project dependencies
  - package-ecosystem: "pip"
    directory: "/" # No top-level requirements.txt specified; remove if not applicable
    schedule:
      interval: "weekly"

  # Dependencies in Metaforge
  - package-ecosystem: "pip"
    directory: "/metaforge"
    schedule:
      interval: "weekly"

  # Dependencies in the individual program folders under modules
  - package-ecosystem: "pip"
    directory: "/modules/chisel"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "pip"
    directory: "/modules/curator"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/modules/filmframe"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/modules/muse"
    schedule:
      interval: "weekly"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
