api_keys:
  pixabay:
    key: 22029602-3043c9fe5af8e35c30dcb94c0
  unsplash:
    key: TcTqyEbiK-FOicvFY5BUmOEBDrfjgm6QZRcUHVTVs9Y
  pexels:
    key: H1vroUbVZJ3SqfcmTl320iBOinQ9m04lOv6VlvYCSl0Hq52bEOmIwHQW
  flickr:
    key: a04580f69e78a8554393f3cf4765012d
  google_cse:
    key: AIzaSyApVIIKdbdcnf_xXBvJ7tcEVP4WM9O3mK8
    search_engine_id: 93e180676b74e4a06

rate_limits:
  pixabay:
    calls: 100
    period: 60
  unsplash:
    calls: 50
    period: 60
  pexels:
    calls: 200
    period: 3600
  flickr:
    calls: 3600
    period: 3600
  google_cse:
    calls: 100
    period: 100

email_settings:
  from_email: your_email@example.com
  smtp_server: smtp.your_email_provider.com
  smtp_port: 587
  smtp_login: your_email_login
  smtp_password: your_email_password
  send_email: true

search_terms:
  - nature
  #- city
  #- animals
  #- space
  #- ocean

max_images: 1