# ================================================
#    _____ _ _            ___                         
#   |  ___(_) |_ __ ___  |  ___|_ __ __ _ _ __ ___   ___ 
#   | |_  | | | '_ ` _ \ | |_ | '__/ _` | '_ ` _ \ / _ \
#   |  _| | | | | | | | ||  _|| | | (_| | | | | | |  __/
#   |_|   |_|_|_| |_| |_||_|  |_|  \__,_|_| |_| |_|\___|
#                                                    
# ================================================

# -----------------------------------------------
# Input/Output Configuration
# -----------------------------------------------
# Specify paths for input movies and output frames
input:
  # Single movie file path or directory containing movies
  path: "path/to/movies"
  # Enable batch mode for processing multiple movies
  batch_mode: false
  # Supported video formats
  supported_formats:
    - .mp4
    - .avi
    - .mov
    - .mkv

output:
  # Base directory for storing extracted frames
  frames_directory: "Frames"
  # Image format for extracted frames
  image_format: "jpg"  # Options: jpg, png, bmp, tiff
  # Image quality (1-100, for jpg format)
  quality: 95

# -----------------------------------------------
# Frame Extraction Settings
# -----------------------------------------------
extraction:
  # Time interval between frames (in seconds)
  interval: 60
  # Minimum frame quality threshold (0-100)
  quality_threshold: 70
  # Whether to extract frames sequentially or based on scene changes
  mode: "interval"  # Options: interval, scene_change
  # Scene change detection sensitivity (if mode is scene_change)
  scene_change_threshold: 30

# -----------------------------------------------
# Metadata Collection
# -----------------------------------------------
metadata:
  # Template for collecting movie information
  required_fields:
    - movie_name
    - year
    - director
    - license
    - url
  # Default license if not specified
  default_license: "Creative Commons Attribution-NonCommercial-ShareAlike 4.0"
  # Metadata storage format
  format: "yaml"  # Options: yaml, json
  # Additional custom fields
  custom_fields:
    - genre
    - language
    - duration

# -----------------------------------------------
# Email Notification Settings
# -----------------------------------------------
email:
  # Enable email notifications
  enabled: false
  smtp:
    server: "smtp.example.com"
    port: 587
    use_tls: true
    username: "your_username"
    password: "your_password"
  notification:
    from_email: "sender@example.com"
    to_email: "recipient@example.com"
    subject: "FilmFrame: Frame Extraction Complete"
    body_template: "Frame extraction has completed for {movie_name}. Total frames extracted: {frame_count}"

# -----------------------------------------------
# Processing Settings
# -----------------------------------------------
processing:
  # Number of parallel processes for batch processing
  max_processes: 4
  # Memory usage limit per process (in MB)
  memory_limit: 1024
  # Enable progress bar
  show_progress: true
  # Skip existing frame files
  skip_existing: true

# -----------------------------------------------
# Logging Configuration
# -----------------------------------------------
logging:
  # Log file location
  file: "filmframe.log"
  # Logging level
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  # Maximum log file size (in MB)
  max_size: 10
  # Number of backup log files to keep
  backup_count: 3
  # Log format
  format: "%(asctime)s - %(levelname)s - %(message)s"

# -----------------------------------------------
# Error Handling
# -----------------------------------------------
error_handling:
  # Maximum retries for failed operations
  max_retries: 3
  # Delay between retries (in seconds)
  retry_delay: 5
  # Whether to continue processing other files after an error
  continue_on_error: true
  # Save error reports
  save_error_report: true
  error_report_path: "error_reports/"

# -----------------------------------------------
# Advanced Settings
# -----------------------------------------------
advanced:
  # Frame filename template
  frame_filename_template: "frame_{frame_number}"
  # Preserve original frame timestamps
  preserve_timestamps: true
  # Enable GPU acceleration if available
  use_gpu: false
  # Temporary directory for processing
  temp_directory: "tmp/"
  # Clean temporary files after processing
  clean_temp: true

# ================================================
#                End of Configuration
# ================================================
