# ================================================
#    _____ _     _          _ 
#   / ____| |   (_)        | |
#  | |    | |__  _ ___  ___| |
#  | |    | '_ \| / __|/ _ \ |
#  | |____| | | | \__ \  __/ |
#   \_____|_| |_|_|___/\___|_|
#
#          Chisel Configuration File
# ================================================

# ----------------------------------------
# Paths Configuration
# ----------------------------------------
paths:
  image_folder: "./images"               # Path to the input folder containing images
  output_folder: "./processed_images"    # Path to the output folder for processed images

# ----------------------------------------
# Target Settings
# ----------------------------------------
target:
  size:                                   # Target size for image resizing (width, height)
    - 256
    - 256
  format: "JPEG"                           # Output format for processed images (JPEG, PNG, etc.)

# ----------------------------------------
# Quality Control Settings
# ----------------------------------------
quality_control:
  min_size: 128                          # Minimum size (in pixels) for image quality
  blur_threshold: 100.0                  # Blur threshold for image quality check

# ----------------------------------------
# Enhancement Factors
# ----------------------------------------
enhancement:
  brightness: 1.0                        # Brightness factor (1.0 = original brightness)
  contrast: 1.0                          # Contrast factor (1.0 = original contrast)
  color: 1.0                             # Color factor (1.0 = original color saturation)
  sharpness: 1.0                         # Sharpness factor (1.0 = original sharpness)

# ----------------------------------------
# Output Quality Settings
# ----------------------------------------
output:
  quality: 85                            # Quality for JPEG output (1-100)

# ----------------------------------------
# Duplicate Detection Settings
# ----------------------------------------
duplicate_detection:
  supported_formats:                     # List of supported image file extensions for processing
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".bmp"
    - ".tiff"

# ----------------------------------------
# Threading Configuration
# ----------------------------------------
threads:
  max_workers: 8                         # Maximum number of threads for concurrent image processing

# ----------------------------------------
# Logging Configuration
# ----------------------------------------
logging:
  level: "INFO"                          # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  log_file: "chisel.log"                 # Path to the log file

# ----------------------------------------
# Duplicate Handling Settings
# ----------------------------------------
duplicate_handling:
  enable_removal: true                   # Enable or disable duplicate removal

# ----------------------------------------
# Database Configuration
# ----------------------------------------
database:
  url: 'sqlite:///metaforge.db'           # Ensure this matches the Curator's database or is accessible by both

# ----------------------------------------
# Metadata Export Settings
# ----------------------------------------
metadata_export:
  export_dir: 'metaforge/exports/chisel'  # Directory to export metadata JSON/YAML files
  formats:                                # Formats to export metadata
    - json
    - yaml

# ================================================
#                End of Configuration
# ================================================
