# ================================================
#    _____ _ _            ___
#   |  ___(_) |_ __ ___  | ___|_ __ __ _ _ __ ___   ___
#   | |_  | | | '_ ` _ \ | |_ | '__/ _` | '_ ` _ \ / _ \
#   |  _| | | | | | | | ||  _|| | | (_| | | | | | |  __/
#   |_|   |_|_|_| |_| |_||_|  |_|  \__,_|_| |_| |_|\___|
#
#          FilmFrame Configuration File
# ================================================
#
# This configuration file manages settings for the FilmFrame module,
# responsible for extracting frames from videos, processing them,
# managing metadata, and integrating with the Metaforge database.

# -----------------------------------------------
# Input Configuration
# -----------------------------------------------
input:
  path: "path/to/movies"                    # Path to the input folder containing movies
  batch_mode: false                         # Enable batch mode for processing multiple movies
  supported_formats:                       # List of supported video formats for processing
    - ".mp4"
    - ".avi"
    - ".mov"
    - ".mkv"
    - ".flv"
    - ".wmv"
    - ".webm"
    - ".mpeg"
    - ".mpg"
    - ".3gp"

# -----------------------------------------------
# Output Configuration
# -----------------------------------------------
output:
  frames_directory: "Frames"                # Directory to store extracted frames
  image_formats:                           # List of image formats to save frames in
    - "jpg"
    - "png"
    - "bmp"
    - "tiff"
  quality: 95                               # Quality setting for JPEG images (1-100)
  overwrite_existing: false                # Overwrite existing frames if True

# -----------------------------------------------
# Frame Extraction Settings
# -----------------------------------------------
extraction:
  interval: 60                              # Time interval between frames in seconds
  mode: "interval"                          # Extraction mode: "interval", "fps", "specific_frames"
  specific_frames: []                       # List of specific frame numbers to extract (used if mode is "specific_frames")
  use_gpu: false                            # Enable GPU acceleration if available

# -----------------------------------------------
# Metadata Settings
# -----------------------------------------------
metadata:
  required_fields:
    - movie_name
    - year
    - director
    - license
    - url
  default_license: "Creative Commons Attribution-NonCommercial-ShareAlike 4.0"  # Default license if not specified
  format: "yaml"                            # Metadata storage format: "yaml" or "json"
  custom_fields:                           # Additional fields to include in metadata
    - genre
    - language
    - duration
    - resolution
    - frame_count

# -----------------------------------------------
# Email Notification Settings (Optional)
# -----------------------------------------------
email:
  enabled: false                            # Enable or disable email notifications
  smtp:
    server: "smtp.example.com"              # Your SMTP server address (e.g., smtp.gmail.com)
    port: 587                               # SMTP server port (e.g., 587 for TLS)
    use_tls: true                           # Use TLS for SMTP connection
    username: "your_username"               # Your SMTP account username
    password: "your_password"               # Your SMTP account password
  notification:
    from_email: "sender@example.com"        # Email address to send from
    to_email: "recipient@example.com"       # Email address to send notifications to
    subject: "FilmFrame: Frame Extraction Complete"  # Subject of the notification email
    body_template: "Frame extraction has completed for {movie_name}. Total frames extracted: {frame_count}"  # Email body template

# -----------------------------------------------
# Processing Settings
# -----------------------------------------------
processing:
  max_processes: 4                          # Number of parallel threads for frame extraction
  show_progress: true                       # Display a progress bar during processing
  skip_existing: true                       # Skip extraction for existing frames to avoid reprocessing
  existing_dir_action: 'ask'                # Options: 'ask', 'overwrite', 'create_new', 'skip'

# -----------------------------------------------
# Logging Configuration
# -----------------------------------------------
logging:
  file: "filmframe.log"                     # Log file path
  level: "INFO"                             # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(levelname)s - %(message)s"  # Log message format

# -----------------------------------------------
# Error Handling Settings
# -----------------------------------------------
error_handling:
  save_error_report: true                   # Enable or disable saving error reports
  error_report_path: "error_reports/"       # Directory to save error reports

# -----------------------------------------------
# Advanced Settings
# -----------------------------------------------
advanced:
  frame_filename_template: "frame_{frame_number}"  # Template for frame filenames
  preserve_timestamps: true                     # Preserve original video timestamps
  use_gpu: false                                # Enable GPU acceleration if available
  frame_resolution:                            # Desired resolution for frames (width, height)
    width: 1920
    height: 1080
  extract_keyframes_only: false                 # Extract only keyframes if true

# -----------------------------------------------
# Database Configuration
# -----------------------------------------------
database:
  url: 'sqlite:///metaforge.db'                # Ensure this matches the Curator's database or is accessible by both

# -----------------------------------------------
# Metadata Export Settings
# -----------------------------------------------
metadata_export:
  export_dir: 'metaforge/exports/filmframe'    # Directory to export metadata JSON/YAML files
  formats:                                     # Formats to export metadata
    - json
    - yaml

# ================================================
#                End of Configuration
# ================================================
