# ================================================
#    _____ _ _            ___
#   |  ___(_) |_ __ ___  | ___|_ __ __ _ _ __ ___   ___
#   | |_  | | | '_ ` _ \ | |_ | '__/ _` | '_ ` _ \ / _ \
#   |  _| | | | | | | | ||  _|| | | (_| | | | | | |  __/
#   |_|   |_|_|_| |_| |_||_|  |_|  \__,_|_| |_| |_|\___|
#
#          FilmFrame Configuration File
# ================================================

# Input Configuration
input:
  path: "path/to/movies"                   # Path to the input folder containing movies
  batch_mode: false                        # Enable batch mode for processing multiple movies
  supported_formats:                      # List of supported video formats for processing
    - .mp4
    - .avi
    - .mov
    - .mkv
    - .flv
    - .wmv
    - .webm
    - .mpeg
    - .mpg
    - .3gp

# Output Configuration
output:
  frames_directory: "Frames"               # Directory to store extracted frames
  image_formats:                           # List of image formats to save frames in
    - "jpg"
    - "png"
    - "bmp"
    - "tiff"
  quality: 95                               # Quality setting for JPEG images

# Frame Extraction Settings
extraction:
  interval: 60                              # Time interval between frames in seconds
  mode: "interval"                          # Extraction mode: "interval"

# Metadata Settings
metadata:
  required_fields:
    - movie_name
    - year
    - director
    - license
    - url
  default_license: "Creative Commons Attribution-NonCommercial-ShareAlike 4.0"
  format: "yaml"                            # Metadata storage format: "yaml" or "json"
  custom_fields:
    - genre
    - language
    - duration

# Email Notification Settings
email:
  enabled: false
  smtp:
    server: "smtp.example.com"
    port: 587
    use_tls: true
    username: "your_username"
    password: "your_password"              # Consider prompting for this instead for security
  notification:
    from_email: "sender@example.com"
    to_email: "recipient@example.com"
    subject: "FilmFrame: Frame Extraction Complete"
    body_template: "Frame extraction has completed for {movie_name}. Total frames extracted: {frame_count}"

# Processing Settings
processing:
  max_processes: 4                          # Number of parallel threads for frame extraction
  show_progress: true                      # Display a progress bar during processing
  skip_existing: true                      # Skip extraction for existing frames to avoid reprocessing
  existing_dir_action: 'ask'               # Options: 'ask', 'overwrite', 'create_new', 'skip'

# Logging Configuration
logging:
  file: "filmframe.log"                     # Log file path
  level: "INFO"                             # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(levelname)s - %(message)s"

# Error Handling Settings
error_handling:
  save_error_report: true                  # Enable or disable saving error reports
  error_report_path: "error_reports/"       # Directory to save error reports

# Advanced Settings
advanced:
  frame_filename_template: "frame_{frame_number}"  # Template for frame filenames
  preserve_timestamps: true                     # Preserve original video timestamps
  use_gpu: false                                # Enable GPU acceleration if available

# Database Configuration
database:
  url: 'sqlite:///metaforge.db'                   # Ensure this matches the Curator's database or is accessible by both

# Metadata Export Settings
metadata_export:
  export_dir: 'metaforge/exports/filmframe'       # Directory to export metadata JSON/YAML files

# ================================================
#                End of Configuration
# ================================================
