# ================================================
#    __  __                
#   |  \/  |_   _ ___  ___ 
#   | |\/| | | | / __|/ _ \
#   | |  | | |_| \__ \  __/
#   |_|  |_|\__,_|___/\___|
#                          
# ================================================

# -----------------------------------------------
# Input and Output Configuration
# -----------------------------------------------
# Specify the paths for input and output folders.
# The input folder should contain preprocessed images from Chisel.
# The output folder will store the organized dataset.

input_folder: "path/to/preprocessed_images"
output_folder: "path/to/output_dataset"

# -----------------------------------------------
# Dataset Splitting Configuration
# -----------------------------------------------
# Define the ratios for splitting the dataset into training, validation, and test sets.
# The sum of these ratios should equal 1.0.

split_ratios:
  - 0.7  # training set
  - 0.2  # validation set
  - 0.1  # test set

# -----------------------------------------------
# Data Augmentation Settings
# -----------------------------------------------
# Configure data augmentation to increase dataset variety and prevent overfitting.

augment: true  # Set to false to disable augmentation

# Types of augmentation to apply
augmentation_types:
  - rotate
  - flip_horizontal
  - mixup
  - cutmix

# Multiplier for augmentation (e.g., 2 will double the dataset size)
augmentation_multiplier: 2

# -----------------------------------------------
# Quality Control Parameters
# -----------------------------------------------
# Set minimum requirements for images to be included in the dataset.

min_size: 256  # Minimum size in pixels (width and height)
allowed_formats:
  - JPEG
  - PNG

# -----------------------------------------------
# Advanced Settings
# -----------------------------------------------
# Additional options for dataset creation and management.

stratify: true  # Maintain class distribution across splits

# -----------------------------------------------
# Logging Configuration
# -----------------------------------------------
# Specify the directory where log files will be stored.
# Ensure that the application has write permissions to this directory.

log_directory: "./logs"

# -----------------------------------------------
# Performance Settings
# -----------------------------------------------
# Configure settings related to processing performance.

batch_size: 32  # Number of images to process in a single batch
num_workers: 4  # Number of parallel workers for data loading

# ================================================
#                End of Configuration
# ================================================
