name: Documentation Improvement
description: Suggest improvements or corrections to MichaelAngel.io's documentation
title: "[Docs] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        ## 📚 Documentation Improvement

        Thank you for helping us improve our documentation! Please provide details about the changes or additions you'd like to see.

  - type: input
    id: doc_title
    attributes:
      label: Section Title
      description: The title of the documentation section to improve
      placeholder: e.g., "Installation Guide"
    validations:
      required: true

  - type: textarea
    id: improvement_details
    attributes:
      label: Improvement Details
      description: Detailed description of the improvement or correction
      placeholder: Explain what needs to be changed or added
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context or examples to support your suggestion
      placeholder: Add any other relevant information here
    validations:
      required: false
