name: Feature Request
description: Suggest a feature or enhancement for MichaelAngel.io
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🌟 Feature Request

        Thank you for your interest in improving MichaelAngel.io! Please provide the following details to help us understand your feature request.

  - type: input
    id: feature_title
    attributes:
      label: Feature Title
      description: A short and descriptive title for your feature request
      placeholder: Describe the feature in a few words
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: Description
      description: A detailed description of the feature
      placeholder: Provide a detailed explanation of the feature you are proposing
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: How will this feature be used?
      placeholder: Describe how you or others will use this feature
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - label: Low 🟢
          value: low
        - label: Medium 🟡
          value: medium
        - label: High 🔴
          value: high
    validations:
      required: true

  - type: textarea
    id: ethical_compliance
    attributes:
      label: Ethical AI & Creative Commons Compliance
      description: Explain how this feature aligns with our ethical AI goals and Creative Commons standards.
      placeholder: Describe how this feature ensures proper attribution, maintains data integrity, and adheres to ethical guidelines.
    validations:
      required: true

  - type: textarea
    id: additional_details
    attributes:
      label: Additional Details
      description: Any other relevant information
      placeholder: Add any other context or screenshots about the feature request here
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        <div align="center">
        
        [![View MichaelAngel.io on GitHub](https://img.shields.io/badge/GitHub-View%20MichaelAngel.io-blue?logo=github)](https://github.com/M1ck4/MichaelAngel.io)
        
        [![Ethical AI](https://img.shields.io/badge/Ethical%20AI-Priority-orange.svg)](https://github.com/M1ck4/MichaelAngel.io/blob/main/docs/the_codex/AI_Artisians_FAQ.md)
        
        ![Creative Commons License](https://img.shields.io/badge/License-CC%20BY--NC--SA%204.0-lightgrey?style=for-the-badge&logo=creative-commons&logoColor=white)
        
        </div>
