name: Security Vulnerability Report
description: Report a security vulnerability in MichaelAngel.io
title: "[Security] "
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🔒 Security Vulnerability Report

        Thank you for helping us keep MichaelAngel.io secure! Please provide detailed information about the vulnerability.

  - type: input
    id: vulnerability_title
    attributes:
      label: Vulnerability Title
      description: A short and descriptive title for the vulnerability
      placeholder: Describe the vulnerability in a few words
    validations:
      required: true

  - type: textarea
    id: vulnerability_description
    attributes:
      label: Vulnerability Description
      description: A detailed description of the vulnerability
      placeholder: Explain the vulnerability and its potential impact
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the vulnerability
      placeholder: Step-by-step instructions
    validations:
      required: true

  - type: textarea
    id: proposed_fix
    attributes:
      label: Proposed Fix
      description: If you have suggestions for fixing the vulnerability, please share them
      placeholder: Describe your proposed solution
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Any other relevant information that might help
      placeholder: Add any other context or details here
    validations:
      required: false
