# ================================================
#    ,-----.                         ,--.                    
#   '  .--./,--.,--.,--.--. ,--,--.,-'  '-. ,---. ,--.--.    
#   |  |    |  ||  ||  .--'' ,-.  |'-.  .-'| .-. ||  .--'    
#   '  '--'\'  ''  '|  |   \ '-'  |  |  |  ' '-' '|  |       
#    `-----' `----' `--'    `--`--'  `--'   `---' `--'
# ================================================
#
#               Curator Configuration File
# ================================================

# -----------------------------------------------
# API Keys for Image Services
# -----------------------------------------------
# Obtain API keys by registering on each service's website.
# It's recommended to use environment variables for sensitive information.
# Replace "YOUR_..." placeholders with actual keys or reference environment variables.

api_keys:
  pixabay:
    key: "YOUR_PIXABAY_API_KEY"  # Replace with your Pixabay API key
  unsplash:
    key: "YOUR_UNSPLASH_API_KEY"  # Replace with your Unsplash API key
  pexels:
    key: "YOUR_PEXELS_API_KEY"  # Replace with your Pexels API key
  flickr:
    key: "YOUR_FLICKR_API_KEY"  # Replace with your Flickr API key
  google_cse:
    key: "YOUR_GOOGLE_CSE_API_KEY"  # Replace with your Google Custom Search API key
    search_engine_id: "YOUR_GOOGLE_CSE_SEARCH_ENGINE_ID"  # Replace with your Google CSE Search Engine ID

# -----------------------------------------------
# Search Terms Configuration
# -----------------------------------------------
# Define the list of search terms for which images will be downloaded.
# Each term should be on a separate line.

search_terms:
  - nature
  - city
  - animals
  - space
  - ocean

# -----------------------------------------------
# Rate Limits for API Calls
# -----------------------------------------------
# Configure rate limits to comply with each API's usage policies.
# Set 'calls' to the maximum number of API requests allowed within the 'period' (in seconds).
# If no rate limit is needed for a service, you can omit its section or set 'calls' to 0.

rate_limits:
  pixabay:
    calls: 100
    period: 60
  unsplash:
    calls: 50
    period: 60
  pexels:
    calls: 200
    period: 3600
  flickr:
    calls: 3600
    period: 3600
  google_cse:
    calls: 100
    period: 100

# -----------------------------------------------
# Download Settings
# -----------------------------------------------
# Define the maximum number of images to download per search term.
# Optionally, set the minimum and maximum resolution for downloaded images.

download_settings:
  max_images_per_term: 100
  min_resolution:
    width: 300
    height: 300
  max_resolution:
    width: 4000
    height: 4000

# -----------------------------------------------
# Duplicate Detection Settings
# -----------------------------------------------
# Configure duplicate detection to avoid downloading duplicate images.
# Enable or disable duplicate detection and specify the method.

duplicate_detection:
  enable: true                           # Enable or disable duplicate detection
  method: "hash"                         # Method for duplicate detection (e.g., "hash", "metadata")
  supported_formats:                     # List of supported image file extensions for processing
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".bmp"
    - ".tiff"

# -----------------------------------------------
# Paths Configuration
# -----------------------------------------------
# Define paths for image storage, metadata export, and logs.

paths:
  image_folder: "./downloaded_images"     # Path to store downloaded images
  metadata_export_dir: "metaforge/exports/curator"  # Directory to export metadata JSON/YAML files
  log_directory: "./logs"                 # Directory to store log files

# -----------------------------------------------
# Logging Configuration
# -----------------------------------------------
# Configure logging settings, including log level and log file name.

logging:
  level: "INFO"                          # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  log_file: "curator.log"                # Log file name

# -----------------------------------------------
# Email Notification Settings (Optional)
# -----------------------------------------------
# Enable email notifications to receive reports upon completion.
# Fill in the SMTP server details and recipient information.
# Ensure that your SMTP server supports the specified port and security settings.

email_settings:
  enable_notifications: false            # Enable or disable email notifications
  smtp_server: "smtp.example.com"        # Your SMTP server address (e.g., smtp.gmail.com)
  smtp_port: 587                         # SMTP server port (e.g., 587 for TLS)
  smtp_login: "your_username"            # Your SMTP account username
  smtp_password: "your_password"         # Your SMTP account password
  from_email: "from@example.com"         # Email address to send from
  to_email: "to@example.com"             # Email address to send notifications to

# -----------------------------------------------
# Database Configuration
# -----------------------------------------------
# Configure the database URL for Metaforge integration.
# Ensure this matches the database URL used by other modules (e.g., Chisel, Muse).

database:
  url: 'sqlite:///metaforge.db'           # Database URI (e.g., sqlite:///metaforge.db or postgresql://user:pass@localhost/dbname)

# ================================================
#                End of Configuration
# ================================================
