# ================================================
#    ,-----.                         ,--.                    
#   '  .--./,--.,--.,--.--. ,--,--.,-'  '-. ,---. ,--.--.    
#   |  |    |  ||  ||  .--'' ,-.  |'-.  .-'| .-. ||  .--'    
#   '  '--'\'  ''  '|  |   \ '-'  |  |  |  ' '-' '|  |       
#    `-----' `----' `--'    `--`--'  `--'   `---' `--'
# ================================================

# -----------------------------------------------
# API Keys for Image Services
# -----------------------------------------------
# Obtain API keys by registering on each service's website.
# Ensure that the keys are kept secure and not shared publicly.

api_keys:
  pixabay:
    key: "YOUR_PIXABAY_API_KEY"  # Replace with your Pixabay API key
  unsplash:
    key: "YOUR_UNSPLASH_API_KEY"  # Replace with your Unsplash API key
  pexels:
    key: "YOUR_PEXELS_API_KEY"  # Replace with your Pexels API key
  flickr:
    key: "YOUR_FLICKR_API_KEY"  # Replace with your Flickr API key
  google_cse:
    key: "YOUR_GOOGLE_CSE_API_KEY"  # Replace with your Google Custom Search API key
    search_engine_id: "YOUR_GOOGLE_CSE_SEARCH_ENGINE_ID"  # Replace with your Google CSE Search Engine ID

# -----------------------------------------------
# Search Terms Configuration
# -----------------------------------------------
# Define the list of search terms for which images will be downloaded.
# Each term should be on a separate line.
# The Search_Terms_Dictionary will have some examples which can be found in the base directory.

search_terms:
  - nature
  - city
  - animals
  - space
  - ocean                                                     
       
                                                   

# -----------------------------------------------
# Rate Limits for API Calls (Optional)
# -----------------------------------------------
# Configure rate limits to comply with each API's usage policies.
# Set 'calls' to the maximum number of API requests allowed within the 'period' (in seconds).
# If no rate limit is needed, you can omit the section or set 'calls' to 0.

rate_limits: #Set for free API limits
  pixabay:
    calls: 100
    period: 60
  unsplash:
    calls: 50
    period: 60
  pexels:
    calls: 200
    period: 3600
  flickr:
    calls: 3600
    period: 3600
  google_cse:
    calls: 100
    period: 100

# -----------------------------------------------
# Download Settings
# -----------------------------------------------
# Define the maximum number of images to download per search term.

max_images_per_term: 100

# -----------------------------------------------
# Logging Configuration
# -----------------------------------------------
# Specify the directory where log files will be stored.
# Ensure that the application has write permissions to this directory.

log_directory: "./logs"

# -----------------------------------------------
# Email Notification Settings (Optional)
# -----------------------------------------------
# Enable email notifications to receive reports upon completion.
# Fill in the SMTP server details and recipient information.
# Ensure that your SMTP server supports the specified port and security settings.

email_settings:
  smtp_server: "smtp.example.com"         # Your SMTP server address (e.g., smtp.gmail.com)
  smtp_port: 587                          # SMTP server port (e.g., 587 for TLS)
  smtp_login: "your_username"             # Your SMTP account username
  smtp_password: "your_password"          # Your SMTP account password
  from_email: "from@example.com"          # Email address to send from
  to_email: "to@example.com"              # Email address to send notifications to

# ================================================
#                End of Configuration
# ================================================

