# ================================================
#    _____ _ _            ___
#   |  ___(_) |_ __ ___  | ___|_ __ __ _ _ __ ___   ___
#   | |_  | | | '_ ` _ \ | |_ | '__/ _` | '_ ` _ \ / _ \
#   |  _| | | | | | | | ||  _|| | | (_| | | | | | |  __/
#   |_|   |_|_|_| |_| |_||_|  |_|  \__,_|_| |_| |_|\___|
#
#          FilmFrame Configuration File
# ================================================

# Input Configuration
input:
  path: "path/to/movies"
  batch_mode: false
  supported_formats:
    - .mp4
    - .avi
    - .mov
    - .mkv
    - .flv
    - .wmv
    - .webm
    - .mpeg
    - .mpg
    - .3gp

# Output Configuration
output:
  frames_directory: "Frames"
  image_formats:  # List of image formats to save frames in
    - "jpg"
    - "png"
    - "bmp"
    - "tiff"
  quality: 95  # Quality setting for JPEG images

# Frame Extraction Settings
extraction:
  interval: 60
  mode: "interval"

# Metadata Settings
metadata:
  required_fields:
    - movie_name
    - year
    - director
    - license
    - url
  default_license: "Creative Commons Attribution-NonCommercial-ShareAlike 4.0"
  format: "yaml"
  custom_fields:
    - genre
    - language
    - duration

# Email Notification Settings
email:
  enabled: false
  smtp:
    server: "smtp.example.com"
    port: 587
    use_tls: true
    username: "your_username"
    password: "your_password"  # You may choose to prompt for this instead
  notification:
    from_email: "sender@example.com"
    to_email: "recipient@example.com"
    subject: "FilmFrame: Frame Extraction Complete"
    body_template: "Frame extraction has completed for {movie_name}. Total frames extracted: {frame_count}"

# Processing Settings
processing:
  max_processes: 4
  show_progress: true
  skip_existing: true
  existing_dir_action: 'ask'

# Logging Configuration
logging:
  file: "filmframe.log"
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"

# Error Handling Settings
error_handling:
  save_error_report: true
  error_report_path: "error_reports/"

# Advanced Settings
advanced:
  frame_filename_template: "frame_{frame_number}"
  preserve_timestamps: true
  use_gpu: false
